import assert from 'node:assert/strict';
import test from 'node:test';
import { appModuleLoader } from '/tmp/adaptive-audit-frozen-r2/scripts/test-support/load-app-module.mjs';
import { discoveryClock,deferred,flush } from '/tmp/adaptive-audit-frozen-r2/scripts/test-support/discovery-clock.mjs';
const load=appModuleLoader();
const {createDateNightHybridSession}=load('src/lib/date-night/hybrid-session.ts');
const {buildDateNightQueryPlan}=load('src/lib/date-night/query-plan.ts');
const {decorateDateNight,eligibleDateNight}=load('src/lib/date-night/eligibility.ts');
const q={lat:43,lon:-79,radiusMiles:50,halloweenActive:true,activityTypes:['movies']};
const row=(i,changes={})=>({id:`v${i}`,name:`Independent Cinema ${i}`,lat:43+i*.01,lon:-79,address:'Control',source:'osm',activityTypes:['movies'],openingHours:'24/7',...changes});
const payload=(query,rows=[])=>({venues:rows,source:'live',...(query.patchId?{patch:{id:query.patchId,version:'radial-v1'}}:{}),discovery:{partial:false,groups:buildDateNightQueryPlan(query.activityTypes,query.halloweenActive).map(g=>({...g,outcome:rows.length?'succeeded-nonempty':'succeeded-empty'}))}});
function setup(t,change={}) {const clock=discoveryClock(t),calls=[],states=[];t.mock.method(console,'warn',()=>{});const session=createDateNightHybridSession();let query={...q,...change};const filters={activityTypes:query.activityTypes,radiusMiles:query.radiusMiles,openNowOnly:false,favoritesOnly:false};const cb={auditView:{selectedTypes:filters.activityTypes,eligible:places=>eligibleDateNight(decorateDateNight(places,query,new Date(Date.now())),filters,query.halloweenActive,{},[],Date.now())},request:(query,signal)=>{const d=deferred();calls.push({query,signal,at:clock.now,...d});return d.promise},onChange:s=>states.push(s)};const update=(c={},retryVersion)=>{query={...query,...c};filters.radiusMiles=query.radiusMiles;session.update(query,{...cb,retryVersion})};update();t.after(()=>session.dispose());return {clock,calls,states,session,filters,update,get state(){return states.at(-1)},async reply(rows=[]){const c=calls.at(-1);c.resolve(payload(c.query,rows));await flush()}}}
async function stop(h,rows,fourth=[]){await h.reply(rows);await h.clock.tick(2000);for(let i=0;i<4;i++){await h.reply(i===3?fourth:[]);if(i<3)await h.clock.tick(2000)}}
test('negative received at stop remains authoritative while four survivors keep pool healthy',async t=>{const h=setup(t);await stop(h,Array.from({length:5},(_,i)=>row(i)),[row(0,{lifecycle:'permanently-closed'})]);assert.equal(h.state.auditPolicy.stopped,true);assert.equal(h.state.auditPolicy.mode,'healthy');assert.equal(h.state.response.venues.find(v=>v.id==='v0').lifecycle,'permanently-closed');h.filters.openNowOnly=true;h.update();await h.clock.tick(10000);assert.equal(h.calls.length,5);assert.equal(h.state.response.venues.some(v=>v.id==='v0'&&!v.lifecycle),false)});
test('rich mixed pool with missing selected category is thin and begins immediately',async t=>{const h=setup(t,{activityTypes:['movies','escape-room']});await h.reply(Array.from({length:6},(_,i)=>row(i)));assert.equal(h.calls.length,2);assert.equal(h.calls[1].at,0);assert.equal(h.state.auditPolicy.mode,'thin')});
test('expiry immediately before fourth settlement prevents healthy stop',async t=>{const h=setup(t);const rows=Array.from({length:4},(_,i)=>row(i));rows[0].activityTypes=['movies','haunted-house'];rows[0].seasonalAvailability={status:'confirmed',checkedAt:'2026-10-01',seasonYear:2026,activeFrom:'2026-10-01',activeUntil:'2026-10-31',endsAt:new Date(Date.now()+7500).toISOString().replace('.000','')};await stop(h,rows);assert.equal(h.state.auditPolicy.stopped,false);assert.equal(h.state.auditPolicy.mode,'thin');assert.equal(h.state.auditPolicy.zeroYieldPatches,0);await h.clock.tick(1000);assert.equal(h.calls.length,6)});
test('explicit retry after early stop resumes missing patch without another disk primary',async t=>{const h=setup(t);await stop(h,Array.from({length:4},(_,i)=>row(i)));h.update({},1);await h.clock.tick(2000);assert.equal(h.calls.length,6);assert.equal(h.calls.at(-1).query.patchId,'radial-v1:20:3');assert.equal(h.calls.filter(c=>!c.query.patchId).length,1);assert.equal(h.state.auditPolicy.stopped,false)});
test('radius change during defer cancels obsolete timer and retains separate disk versus patch authority',async t=>{const h=setup(t);await h.reply(Array.from({length:4},(_,i)=>row(i)));await h.clock.tick(1500);h.update({radiusMiles:20});await h.clock.tick(500);assert.equal(h.calls.length,1);await h.clock.tick(1500);assert.equal(h.calls.length,2);assert.equal(h.calls[1].query.radiusMiles,20);assert.equal(h.state.coverage.complete,false);assert.equal(h.state.coverage.continuousRadiusMiles,0)});
test('early-stop incompleteness remains explicit after local filter makes current pool empty',async t=>{const h=setup(t);await stop(h,Array.from({length:4},(_,i)=>row(i)));h.filters.favoritesOnly=true;h.update();const {dateNightHybridProgress}=load('src/lib/date-night/hybrid-session.ts');const message=dateNightHybridProgress(h.state.phase,h.state.expanding);t.diagnostic(JSON.stringify({phase:h.state.phase,stopped:h.state.auditPolicy.stopped,coverageComplete:h.state.coverage.complete,message,requests:h.calls.length}));assert.match(message,/incomplete|paused|unsearched/i)});
