import type { DateNightPlace } from "./types";

// Jasper County Date Night safety net, re-audited September 2026.
// Live OpenStreetMap discovery remains the broad source; this catalog guarantees
// verified local anchors and provides fallback results when live lookup fails.
export const JASPER_COUNTY_DATE_NIGHT_CATALOG: DateNightPlace[] = [
  {
    id: "date-night-tilt-studio-joplin",
    name: "Tilt Studio Joplin",
    lat: 37.0907455,
    lon: -94.4752036,
    address: "101 N Rangeline Rd, Joplin, MO 64801",
    cuisines: ["other"],
    cuisineLabel: "Arcade / Mini Golf",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "Mo-Sa 10:00-20:00; Su 12:00-18:00",
    phone: "+1 417-553-7902",
    website: "https://tiltstudio.com/joplin/",
    isChain: true,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["arcade", "mini-golf", "bowling"],
    moodLevel: 2,
  },
  {
    id: "date-night-fourth-street-bowl-joplin",
    name: "Carl Richard's 4th Street Bowl",
    lat: 37.0885665,
    lon: -94.5301335,
    address: "1419 W 4th St, Joplin, MO 64801",
    cuisines: ["other"],
    cuisineLabel: "Bowling / Arcade",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours:
      "Mo 11:00-22:00; Tu 16:00-22:00; We 11:00-22:00; Th 12:00-22:00; Fr 11:00-23:00; Sa 09:00-23:00; Su 16:00-22:00",
    phone: "+1 417-624-5681",
    website: "https://www.carlrichardsbowl.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["bowling", "arcade"],
    moodLevel: 2,
  },
  {
    id: "date-night-roller-city-joplin",
    name: "Roller City Entertainment",
    lat: 37.063706,
    lon: -94.483519,
    address: "2800 E 24th St, Joplin, MO 64804",
    cuisines: ["other"],
    cuisineLabel: "Skating / Arcade",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "Mo-Tu off; We-Th 16:00-20:00; Fr 16:00-21:00; Sa 12:00-22:00; Su 12:00-19:00",
    phone: "+1 417-781-4033",
    website: "https://rollercitymo.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["skating", "arcade"],
    moodLevel: 3,
  },
  {
    id: "date-night-rangeline-golf-joplin",
    name: "Rangeline Golf Center",
    lat: 37.108371,
    lon: -94.476249,
    address: "2001 N Range Line Rd, Joplin, MO 64801",
    cuisines: ["other"],
    cuisineLabel: "Mini Golf / Games",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "Su-Th 08:00-21:00; Fr-Sa 08:00-22:00",
    phone: "+1 417-624-0400",
    website: "https://rangelinegolf.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["mini-golf", "arcade"],
    moodLevel: 2,
  },
  {
    id: "date-night-route-66-theater-webb-city",
    name: "Route 66 Theater",
    lat: 37.14,
    lon: -94.46298,
    address: "24 S Main St, Webb City, MO 64870",
    cuisines: ["other"],
    cuisineLabel: "Movies",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: "+1 417-317-1414",
    website: "https://route66movietheater.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["movies"],
    moodLevel: 1,
  },
  {
    id: "date-night-66-drive-in-carthage",
    name: "66 Drive-In Theatre",
    lat: 37.173404,
    lon: -94.368582,
    address: "17231 Old 66 Blvd, Carthage, MO",
    cuisines: ["other"],
    cuisineLabel: "Drive-In Movies",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: "+1 417-359-5959",
    website: "https://66drivein.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["movies"],
    moodLevel: 1,
  },
  {
    id: "date-night-precious-moments-chapel",
    name: "Precious Moments Chapel",
    lat: 37.11183,
    lon: -94.34532,
    address: "4321 Chapel Road, Carthage, MO 64836",
    cuisines: ["other"],
    cuisineLabel: "Chapel / Museum / Gardens",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "Mo-Su 09:00-17:00",
    phone: "+1 800-543-7975",
    website: "https://preciousmomentschapel.org/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["museum"],
    moodLevel: 1,
  },
  {
    id: "date-night-battle-of-carthage-museum",
    name: "Battle of Carthage Civil War Museum",
    lat: 37.177569,
    lon: -94.309858,
    address: "205 Grant St, Carthage, MO 64836",
    cuisines: ["other"],
    cuisineLabel: "Museum",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "Mo off; Tu-Sa 08:30-17:00; Su 13:00-17:00",
    phone: "+1 417-237-7060",
    website: "https://www.carthagemo.gov/page/civil-war-museum",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["museum"],
    moodLevel: 1,
  },
  {
    id: "date-night-joplin-museum",
    name: "Joplin History & Mineral Museum",
    lat: 37.08767,
    lon: -94.55045,
    address: "504 S Schifferdecker Ave, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Museum",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "Mo off; Tu-Sa 10:00-17:00; Su off",
    phone: "+1 417-623-1180",
    website: "https://www.joplin-museum.org/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["museum"],
    moodLevel: 1,
  },
  {
    id: "date-night-schifferdecker-park-joplin",
    name: "Schifferdecker Park",
    lat: 37.088672,
    lon: -94.553559,
    address: "Schifferdecker Ave, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Park",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "07:00-23:00",
    phone: null,
    website: "https://www.joplinmo.org/Facilities",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 1,
  },
  {
    id: "date-night-cunningham-park-joplin",
    name: "Cunningham Park",
    lat: 37.0645056,
    lon: -94.5313362,
    address: "W 26th St & S Maiden Ln, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Park",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "07:00-23:00",
    phone: null,
    website: "https://www.joplinmo.org/Facilities",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 1,
  },
  {
    id: "date-night-hatten-park-webb-city",
    name: "Hatten Park",
    lat: 37.1486696,
    lon: -94.4824485,
    address: "354 N College Ave, Webb City, MO 64870",
    cuisines: ["other"],
    cuisineLabel: "Park",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: "https://www.webbcitymo.org/parks-recreation",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 1,
  },
  {
    id: "date-night-king-jack-park-webb-city",
    name: "King Jack Park",
    lat: 37.1352,
    lon: -94.4641,
    address: "555 S Main St, Webb City, MO",
    cuisines: ["other"],
    cuisineLabel: "Park",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: "https://webbcityrec.com/KingJack.aspx",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 1,
  },
  {
    id: "date-night-kellogg-lake-park-carthage",
    name: "Kellogg Lake Park",
    lat: 37.18728,
    lon: -94.294667,
    address: "Jiminy Ln, Carthage, MO",
    cuisines: ["other"],
    cuisineLabel: "Park / Disc Golf",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: null,
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 2,
  },
  {
    id: "date-night-stebbins-park-sarcoxie",
    name: "Stebbins Memorial Park",
    lat: 37.0692,
    lon: -94.1290167,
    address: "Center St & Clarence St, Sarcoxie, MO",
    cuisines: ["other"],
    cuisineLabel: "Park",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: "https://www.sarcoxiemo.gov/parks",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 1,
  },
];
