import type { DateNightPlace } from "./types";

// Jasper County Date Night safety net, audited September 2026.
// Live OpenStreetMap discovery remains the broad source; this catalog guarantees
// verified local anchors and provides fallback results when live lookup fails.
export const JASPER_COUNTY_DATE_NIGHT_CATALOG: DateNightPlace[] = [
  {
    id: "date-night-tilt-studio-joplin",
    name: "Tilt Studio Joplin",
    lat: 37.0907455,
    lon: -94.4752036,
    address: "101 N Range Line Rd, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Arcade / Mini Golf",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: "https://tiltstudio.com/locations/joplin-mo/",
    isChain: true,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["arcade", "mini-golf", "bowling"],
    moodLevel: 2,
  },
  {
    id: "date-night-fourth-street-bowl-joplin",
    name: "Carl Richard's 4th Street Bowl",
    lat: 37.0885665,
    lon: -94.5301335,
    address: "1419 W 4th St, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Bowling / Arcade",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: "https://www.carlrichardsbowl.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["bowling", "arcade"],
    moodLevel: 2,
  },
  {
    id: "date-night-roller-city-joplin",
    name: "Roller City Entertainment",
    lat: 37.063706,
    lon: -94.483519,
    address: "2800 E 24th St, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Skating / Arcade",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: "+1 417-781-4033",
    website: "https://rollercitymo.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["skating", "arcade"],
    moodLevel: 3,
  },
  {
    id: "date-night-rangeline-golf-joplin",
    name: "Rangeline Golf Center",
    lat: 37.108371,
    lon: -94.476249,
    address: "2001 N Range Line Rd, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Mini Golf / Games",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: "+1 417-624-0400",
    website: "https://rangelinegolf.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["mini-golf", "arcade"],
    moodLevel: 2,
  },
  {
    id: "date-night-route-66-theater-webb-city",
    name: "Route 66 Theater",
    lat: 37.14,
    lon: -94.46298,
    address: "24 S Main St, Webb City, MO",
    cuisines: ["other"],
    cuisineLabel: "Movies",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: null,
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["movies"],
    moodLevel: 1,
  },
  {
    id: "date-night-66-drive-in-carthage",
    name: "66 Drive-In Theatre",
    lat: 37.173404,
    lon: -94.368582,
    address: "17231 Old 66 Blvd, Carthage, MO",
    cuisines: ["other"],
    cuisineLabel: "Drive-In Movies",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: "+1 417-359-5959",
    website: "https://66drivein.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["movies"],
    moodLevel: 1,
  },
  {
    id: "date-night-joplin-museum",
    name: "Joplin History & Mineral Museum",
    lat: 37.08767,
    lon: -94.55045,
    address: "504 S Schifferdecker Ave, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Museum",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: "+1 417-623-1180",
    website: "https://www.joplin-museum.org/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["museum"],
    moodLevel: 1,
  },
  {
    id: "date-night-schifferdecker-park-joplin",
    name: "Schifferdecker Park",
    lat: 37.088672,
    lon: -94.553559,
    address: "Schifferdecker Ave, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Park",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "07:00-23:00",
    phone: null,
    website: "https://www.joplinmo.org/Facilities",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 1,
  },
  {
    id: "date-night-cunningham-park-joplin",
    name: "Cunningham Park",
    lat: 37.0645056,
    lon: -94.5313362,
    address: "W 26th St & S Maiden Ln, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Park",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "07:00-23:00",
    phone: null,
    website: "https://www.joplinmo.org/Facilities",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 1,
  },
  {
    id: "date-night-hatten-park-webb-city",
    name: "Hatten Park",
    lat: 37.1486696,
    lon: -94.4824485,
    address: "Webb City, MO",
    cuisines: ["other"],
    cuisineLabel: "Park",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: "https://www.webbcitymo.org/parks-recreation",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 1,
  },
  {
    id: "date-night-king-jack-park-webb-city",
    name: "King Jack Park",
    lat: 37.1352,
    lon: -94.4641,
    address: "555 S Main St, Webb City, MO",
    cuisines: ["other"],
    cuisineLabel: "Park",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: "https://webbcityrec.com/KingJack.aspx",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 1,
  },
  {
    id: "date-night-kellogg-lake-park-carthage",
    name: "Kellogg Lake Park",
    lat: 37.18728,
    lon: -94.294667,
    address: "Jiminy Ln, Carthage, MO",
    cuisines: ["other"],
    cuisineLabel: "Park / Disc Golf",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: null,
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 2,
  },
  {
    id: "date-night-stebbins-park-sarcoxie",
    name: "Stebbins Memorial Park",
    lat: 37.0692,
    lon: -94.1290167,
    address: "Center St & Clarence St, Sarcoxie, MO",
    cuisines: ["other"],
    cuisineLabel: "Park",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: "https://www.sarcoxiemo.gov/parks",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["park"],
    moodLevel: 1,
  },
];
