import type { DateNightPlace } from "./types";

// Seasonal Jasper County Date Night anchors.
// Pins were geocoded from published addresses. 2026 open nights and hours
// are NOT independently verified — keep hours unknown and treat these as
// experimental seasonal fallbacks, not audited year-round catalog records.
export const JASPER_COUNTY_SEASONAL_DATE_NIGHT_CATALOG: DateNightPlace[] = [
  {
    id: "date-night-werehouse-joplin",
    name: "The Werehouse",
    lat: 37.0694258,
    lon: -94.4688601,
    address: "3819 E 20th St, Joplin, MO 64801",
    cuisines: ["other"],
    cuisineLabel: "Haunted House",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: "+1 417-396-6094",
    website: "https://www.missourihauntedhouses.com/halloween/haunted-house-joplin.html",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["haunted-house"],
    moodLevel: 3,
  },
  {
    id: "date-night-myers-forest-carthage",
    name: "Myers Forest of Fears",
    lat: 37.118709,
    lon: -94.311614,
    address: "3935 S Garrison Ave, Carthage, MO 64836",
    cuisines: ["other"],
    cuisineLabel: "Haunted Forest",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: "+1 417-543-2791",
    website: "https://www.missourihauntedhouses.com",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["haunted-house"],
    moodLevel: 3,
  },
  {
    id: "date-night-myers-inn-carthage",
    name: "Myer's Inn Haunt",
    lat: 37.1475746,
    lon: -94.3173348,
    address: "529 W Airport Dr, Carthage, MO 64836",
    cuisines: ["other"],
    cuisineLabel: "Haunted House",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: "https://www.missourihauntedhouses.com",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["haunted-house"],
    moodLevel: 3,
  },
  {
    id: "date-night-jasper-escape-maze",
    name: "Jasper Escape Maze",
    lat: 37.3328563,
    lon: -94.3165544,
    address: "14607 Tamarack Rd, Jasper, MO 64755",
    cuisines: ["other"],
    cuisineLabel: "Corn Maze",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: null,
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["corn-maze"],
    moodLevel: 2,
  },
  {
    id: "date-night-waco-schoolhouse",
    name: "Waco School House Haunt",
    lat: 37.2436228,
    lon: -94.5964668,
    address: "148 Rose St, Waco, MO 64832",
    cuisines: ["other"],
    cuisineLabel: "Haunted House",
    priceLevel: null,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: null,
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    activityTypes: ["haunted-house"],
    moodLevel: 3,
  },
];
