import type { CatalogEntry } from "./catalog";

// Second verification pass for known stale Joplin records discovered during
// the September 2026 audit.
export const SECOND_PASS_REPLACED_IDS = new Set<string>([
  "local-finns",
  "local-kinnaree",
  "local-magic-noodle",
  "local-stogeys",
  "local-dudes",
  "local-club-609",
]);

// Names that should not be allowed back in from stale live map data.
export const RETIRED_LOCAL_NAMES = ["finn's", "finns"] as const;

export const SECOND_PASS_LOCAL_CATALOG: CatalogEntry[] = [
  {
    matchNames: ["kinnaree", "kinnaree thai", "kinnaree thai cuisine"],
    id: "local-kinnaree",
    name: "Kinnaree Thai Cuisine",
    lat: 37.05472,
    lon: -94.49905,
    address: "1227 E 32nd St, Suite 1, Joplin, MO",
    cuisines: ["thai", "international"],
    cuisineLabel: "Thai",
    priceLevel: 2,
    rating: 4.6,
    reviewCount: 115,
    openingHours: "Mo-Fr 11:00-20:00; Sa-Su off",
    phone: "+1 417-781-4442",
    website: "https://www.kinnareejomo.com/",
    isChain: false,
    photoKey: "thai",
  },
  {
    matchNames: ["magic noodle", "the magic noodle", "magic noodle inc"],
    id: "local-magic-noodle",
    name: "Magic Noodle",
    lat: 37.08075,
    lon: -94.47765,
    address: "804 S Range Line Rd, Joplin, MO",
    cuisines: ["thai", "chinese", "international"],
    cuisineLabel: "Thai / Noodles",
    priceLevel: 2,
    rating: 4.2,
    reviewCount: 92,
    openingHours: "Mo off; Tu-Th 11:00-21:00; Fr-Sa 11:00-21:30; Su 11:30-21:00",
    phone: "+1 417-625-1199",
    isChain: false,
    photoKey: "thai",
  },
  {
    matchNames: ["stogey's", "stogeys", "stogey's coney island", "stogeys coney island"],
    id: "local-stogeys",
    name: "Stogey's Coney Island",
    lat: 37.08389,
    lon: -94.48545,
    address: "2629 E 7th St, Joplin, MO",
    cuisines: ["american", "sandwiches", "burgers"],
    cuisineLabel: "American / Coney Island",
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 51,
    openingHours: "Mo-Tu 10:45-16:00; We-Fr 10:45-20:00; Sa 10:45-16:00; Su off",
    phone: "+1 417-623-2020",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["dude's daylight donut", "dudes daylight donut", "dude's daylight donut shop"],
    id: "local-dudes",
    name: "Dude's Daylight Donut Shop",
    lat: 37.0652,
    lon: -94.5141,
    address: "2316 S Main St, Joplin, MO",
    cuisines: ["bakery", "dessert", "breakfast", "coffee"],
    cuisineLabel: "Bakery / Donuts",
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 38,
    openingHours: "Mo-Sa 05:00-17:00; Su off",
    phone: "+1 417-623-6204",
    isChain: false,
    photoKey: "dessert",
  },
  {
    matchNames: ["club 609", "club 609 restaurant & bar", "club 609 restaurant and bar"],
    id: "local-club-609",
    name: "Club 609",
    lat: 37.085091,
    lon: -94.513224,
    address: "609 S Main St, Joplin, MO",
    cuisines: ["american", "sandwiches", "steakhouse"],
    cuisineLabel: "American / Restaurant & Bar",
    priceLevel: 2,
    rating: 4.3,
    reviewCount: 90,
    openingHours: "Mo-Th 11:00-21:00; Fr-Sa 11:00-22:00; Su off",
    phone: "+1 417-623-6090",
    website: "https://club609.com/",
    isChain: false,
    photoKey: "american",
  },
];
