import type { CatalogEntry } from "./catalog";

// Curated local data refreshed in September 2026.
// Live OpenStreetMap discovery remains the broad source of truth; these entries
// correct stale local records and guarantee important Joplin/Carthage places
// remain available when live map data is incomplete or temporarily unavailable.

export const REPLACED_CATALOG_IDS = new Set<string>([
  "local-bruncheonette",
  "local-mythos",
  "local-wilders",
  "local-thai-time",
  "local-crabbys",
  "local-red-onion",
  "local-hungry-monkey",
  "local-club-1201",
  "local-bricktown",
  "local-hackett",
  "local-lalos",
  "local-normas",
]);

export const REFRESHED_LOCAL_CATALOG: CatalogEntry[] = [
  {
    matchNames: ["the bruncheonette", "bruncheonette"],
    id: "local-bruncheonette",
    name: "The Bruncheonette",
    lat: 37.094422,
    lon: -94.513136,
    address: "424 N Main St, Joplin, MO",
    cuisines: ["breakfast", "brunch", "sandwiches", "cafe"],
    cuisineLabel: "Breakfast / Brunch",
    priceLevel: 1,
    rating: 4.7,
    reviewCount: 315,
    openingHours: "Mo-Tu off; We-Fr 08:30-14:00; Sa-Su 09:00-13:00",
    phone: "+1 417-781-3447",
    website: "https://www.thebruncheonette.net/",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["mythos", "mythos euro greek kuzina"],
    id: "local-mythos",
    name: "Mythos",
    lat: 37.076145,
    lon: -94.477717,
    address: "1306 S Range Line Rd, Joplin, MO",
    cuisines: ["greek", "mediterranean", "steakhouse"],
    cuisineLabel: "Greek / Mediterranean",
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 227,
    openingHours: "Mo-Th 11:00-21:00; Fr-Sa 11:00-21:30; Su off",
    phone: "+1 417-624-6984",
    isChain: false,
    photoKey: "mediterranean",
  },
  {
    matchNames: ["wilder's steakhouse", "wilders steakhouse", "wilder's", "wilders steak house"],
    id: "local-wilders",
    name: "Wilder's Steakhouse",
    lat: 37.077795,
    lon: -94.513875,
    address: "1216 S Main St, Joplin, MO",
    cuisines: ["steakhouse", "american", "seafood"],
    cuisineLabel: "Steakhouse",
    priceLevel: 3,
    rating: 4.5,
    reviewCount: 154,
    openingHours: "Mo-Sa 17:00-21:30; Su off",
    phone: "+1 417-623-7230",
    isChain: false,
    photoKey: "steak",
  },
  {
    matchNames: ["thai time", "thai time cafe", "thai time express"],
    id: "local-thai-time",
    name: "Thai Time Express",
    lat: 37.054724,
    lon: -94.492788,
    address: "1804 E 32nd St, Joplin, MO",
    cuisines: ["thai", "international"],
    cuisineLabel: "Thai",
    priceLevel: 2,
    rating: 4.4,
    reviewCount: 265,
    openingHours: "Mo 11:00-15:00,16:00-21:00; Tu off; We-Su 11:00-15:00,16:00-21:00",
    phone: "+1 417-781-0055",
    isChain: false,
    photoKey: "thai",
  },
  {
    matchNames: ["crabby", "crabby's", "crabbys", "crabby's seafood"],
    id: "local-crabbys",
    name: "Crabby's",
    lat: 37.08428,
    lon: -94.5221,
    address: "815 W 7th St, Joplin, MO",
    cuisines: ["seafood", "american"],
    cuisineLabel: "Seafood",
    priceLevel: 3,
    rating: 4.2,
    reviewCount: 239,
    openingHours: "unknown",
    phone: "+1 417-206-3474",
    isChain: false,
    photoKey: "seafood",
  },
  {
    matchNames: ["red onion cafe", "red onion"],
    id: "local-red-onion",
    name: "Red Onion Cafe",
    lat: 37.087765,
    lon: -94.512057,
    address: "203 E 4th St, Joplin, MO",
    cuisines: ["american", "cafe", "sandwiches"],
    cuisineLabel: "American / Casual",
    priceLevel: 2,
    rating: 4.6,
    reviewCount: 694,
    openingHours: "Mo off; Tu-Sa 11:00-21:00; Su off",
    phone: "+1 417-623-1004",
    website: "https://redonionrestaurants.com/",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["hungry monkey", "hungry monkey island style eats"],
    id: "local-hungry-monkey",
    name: "Hungry Monkey Island Style Eats",
    lat: 37.0813,
    lon: -94.5136,
    address: "905 S Main St, Suite 3, Joplin, MO",
    cuisines: ["healthy", "seafood", "international"],
    cuisineLabel: "Hawaiian / Poke",
    priceLevel: 2,
    rating: 4.7,
    reviewCount: 50,
    openingHours: "Mo off; Tu-Sa 11:00-19:00; Su off",
    phone: "+1 417-572-5979",
    isChain: false,
    photoKey: "seafood",
  },
  {
    matchNames: ["club 1201"],
    id: "local-club-1201",
    name: "Club 1201",
    lat: 37.05472,
    lon: -94.5002,
    address: "1201 E 32nd St, Joplin, MO",
    cuisines: ["american", "brunch"],
    cuisineLabel: "American / Brunch",
    priceLevel: 2,
    rating: 4.2,
    reviewCount: 80,
    openingHours: "Mo off; Tu-Th 11:00-15:00; Fr 11:00-21:00; Sa-Su 09:00-14:00",
    phone: "+1 417-626-0032",
    website: "https://www.club1201.com/",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["bricktown brewery", "bricktown"],
    id: "local-bricktown",
    name: "Bricktown Brewery",
    lat: 37.056856,
    lon: -94.478963,
    address: "3030 S Range Line Rd, Joplin, MO",
    cuisines: ["american", "burgers"],
    cuisineLabel: "American / Brewpub",
    priceLevel: 2,
    rating: 4.4,
    reviewCount: 131,
    openingHours: "Su-Th 11:00-21:00; Fr-Sa 11:00-22:00",
    isChain: true,
    photoKey: "american",
  },
  {
    matchNames: ["hackett hot wings", "hackett's hot wings"],
    id: "local-hackett",
    name: "Hackett Hot Wings",
    lat: 37.086032,
    lon: -94.51369,
    address: "520 S Main St, Joplin, MO",
    cuisines: ["wings", "chicken", "american"],
    cuisineLabel: "Wings / Sports Bar",
    priceLevel: 2,
    rating: 4.1,
    reviewCount: 140,
    openingHours: "Mo off; Tu-Th 11:00-21:00; Fr-Sa 11:00-22:00; Su 11:00-21:00",
    phone: "+1 417-625-1333",
    website: "https://hacketthotwings.com/",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["lalo's taqueria", "lalos taqueria"],
    id: "local-lalos",
    name: "Lalo's Taqueria",
    lat: 37.0839,
    lon: -94.4867,
    address: "2501 E 7th St, Joplin, MO",
    cuisines: ["mexican"],
    cuisineLabel: "Mexican",
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 84,
    openingHours: "Mo-Sa 10:30-19:00; Su off",
    isChain: false,
    photoKey: "mexican",
  },
  {
    matchNames: ["norma's diner", "normas diner", "norma's kitchen"],
    id: "local-normas",
    name: "Norma's Diner",
    lat: 37.0707,
    lon: -94.5141,
    address: "1901 S Main St, Joplin, MO",
    cuisines: ["american", "breakfast", "southern"],
    cuisineLabel: "American / Diner",
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 42,
    openingHours: "Mo off; Tu-Sa 06:00-15:00; Su 06:00-14:00",
    phone: "+1 417-623-6262",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["queen of pho", "queen of phở", "queen of pho nro em"],
    id: "local-queen-of-pho",
    name: "Queen of Phở",
    lat: 37.054303,
    lon: -94.479814,
    address: "2914 E 32nd St, Suite 110, Joplin, MO",
    cuisines: ["international", "other"],
    cuisineLabel: "Vietnamese / Pho",
    priceLevel: 2,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo-Sa 10:30-20:30; Su off",
    phone: "+1 417-313-1122",
    isChain: false,
    photoKey: "asian",
  },
  {
    matchNames: ["red onion espressoria", "red onion cafe 32nd", "red onion cafe"],
    id: "local-red-onion-32nd",
    name: "Red Onion Espressoria",
    lat: 37.05475,
    lon: -94.5029,
    address: "1007 E 32nd St, Joplin, MO",
    cuisines: ["american", "cafe", "sandwiches"],
    cuisineLabel: "American / Cafe",
    priceLevel: 2,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo off; Tu-Sa 11:00-20:00; Su off",
    phone: "+1 417-781-4999",
    website: "https://redonionrestaurants.com/",
    isChain: false,
    photoKey: "cafe",
  },

  // Carthage
  {
    matchNames: ["carthage family restaurant"],
    id: "local-carthage-family",
    name: "Carthage Family Restaurant",
    lat: 37.179677,
    lon: -94.314204,
    address: "125 N Garrison Ave, Carthage, MO",
    cuisines: ["american", "breakfast", "southern"],
    cuisineLabel: "American / Family Diner",
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 76,
    openingHours: "Mo-Sa 06:00-20:00; Su 06:00-15:00",
    phone: "+1 417-359-8411",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["habaneros", "habaneros mexican grill", "habanero's mexican restaurant + cantina"],
    id: "local-habaneros-carthage",
    name: "Habaneros Mexican Restaurant + Cantina",
    lat: 37.1799,
    lon: -94.3117,
    address: "100 Lincoln St, Carthage, MO",
    cuisines: ["mexican", "tex-mex"],
    cuisineLabel: "Mexican / Cantina",
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 109,
    openingHours: "Mo-We 11:00-21:00; Th 11:00-22:00; Fr 11:00-22:30; Sa 11:00-22:00; Su 11:00-21:00",
    phone: "+1 417-237-9335",
    isChain: false,
    photoKey: "mexican",
  },
  {
    matchNames: ["mis arcos", "mis arcos mexican restaurant"],
    id: "local-mis-arcos-carthage",
    name: "Mis Arcos Mexican Restaurant",
    lat: 37.155521,
    lon: -94.314151,
    address: "1926 S Garrison Ave, Carthage, MO",
    cuisines: ["mexican", "tex-mex", "seafood"],
    cuisineLabel: "Mexican",
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 48,
    openingHours: "Mo-Th 11:00-21:00; Fr 11:00-21:30; Sa-Su 11:00-21:00",
    phone: "+1 417-237-0547",
    website: "https://misarcoscarthage.com/",
    isChain: false,
    photoKey: "mexican",
  },
  {
    matchNames: ["iggy's diner", "iggys diner"],
    id: "local-iggys-carthage",
    name: "Iggy's Diner",
    lat: 37.147061,
    lon: -94.310015,
    address: "2400 S Grand Ave, Carthage, MO",
    cuisines: ["american", "breakfast", "southern"],
    cuisineLabel: "American / Route 66 Diner",
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 114,
    openingHours: "Mo-Sa 06:00-21:00; Su 06:00-15:00",
    phone: "+1 417-237-0212",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["lucky j", "lucky j steakhouse", "lucky j steakhouse & arena"],
    id: "local-lucky-j-carthage",
    name: "Lucky J Steakhouse & Arena",
    lat: 37.137524,
    lon: -94.268333,
    address: "11664 E Fir Rd, Carthage, MO",
    cuisines: ["steakhouse", "american", "burgers"],
    cuisineLabel: "Steakhouse / Arena",
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 128,
    openingHours: "Mo-Fr 17:00-22:00; Sa 11:00-22:00; Su 11:00-15:00",
    phone: "+1 417-358-2370",
    website: "https://luckyjarena.com/steakhouse/",
    isChain: false,
    photoKey: "steak",
  },
  {
    matchNames: ["uskana pizza", "uskana"],
    id: "local-uskana-carthage",
    name: "Uskana Pizza",
    lat: 37.168,
    lon: -94.3142,
    address: "910 Garrison Ave, Carthage, MO",
    cuisines: ["pizza", "italian"],
    cuisineLabel: "Pizza / Italian",
    priceLevel: 2,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo off; Tu-Su 16:00-21:00",
    website: "https://www.uskanapizza.com/",
    isChain: false,
    photoKey: "pizza",
  },
  {
    matchNames: ["tacos y mariscos gonzalez", "tacos y mariscos gonzález"],
    id: "local-tacos-mariscos-carthage",
    name: "Tacos y Mariscos Gonzalez",
    lat: 37.176153,
    lon: -94.311236,
    address: "125 W 4th St, Carthage, MO",
    cuisines: ["mexican", "seafood"],
    cuisineLabel: "Mexican / Seafood",
    priceLevel: 1,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo off; Tu-Sa 11:00-21:00; Su 11:00-16:30",
    phone: "+1 417-313-2132",
    isChain: false,
    photoKey: "mexican",
  },
  {
    matchNames: ["the woodshed", "woodshed", "the woodshed burger house", "the woodshed steak & burger house"],
    id: "local-woodshed-carthage",
    name: "The Woodshed Steak & Burger House",
    lat: 37.17677,
    lon: -94.31139,
    address: "311 S Main St, Carthage, MO",
    cuisines: ["american", "burgers", "steakhouse"],
    cuisineLabel: "Steakhouse / Burgers",
    priceLevel: 2,
    rating: 4.8,
    reviewCount: 37,
    openingHours: "unknown",
    phone: "+1 417-358-2707",
    isChain: false,
    photoKey: "steak",
  },
  {
    matchNames: ["whisler's drive-up", "whislers drive-up", "whisler's"],
    id: "local-whislers-carthage",
    name: "Whisler's Drive-Up",
    lat: 37.1819,
    lon: -94.3142,
    address: "300 N Garrison Ave, Carthage, MO",
    cuisines: ["burgers", "american", "fast_food"],
    cuisineLabel: "Burgers / Drive-Up",
    priceLevel: 1,
    rating: 4.8,
    reviewCount: 271,
    openingHours: "Mo-Sa 10:00-18:00; Su off",
    phone: "+1 417-358-4951",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["maple leaf coffeehouse & smootherie", "maple leaf coffeehouse and smootherie", "maple leaf smootherie"],
    id: "local-maple-leaf-smootherie-carthage",
    name: "Maple Leaf Coffeehouse & Smootherie",
    lat: 37.15083,
    lon: -94.312835,
    address: "2206 S Maple St, Suite C-2, Carthage, MO",
    cuisines: ["cafe", "coffee", "breakfast", "brunch"],
    cuisineLabel: "Coffee / Breakfast",
    priceLevel: 1,
    rating: 4.9,
    reviewCount: 223,
    openingHours: "Mo-Fr 06:00-14:00; Sa 07:00-13:00; Su off",
    phone: "+1 417-237-9137",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["maple leaf coffeehouse & creperie", "maple leaf coffeehouse and creperie", "maple leaf creperie"],
    id: "local-maple-leaf-creperie-carthage",
    name: "Maple Leaf Coffeehouse & Creperie",
    lat: 37.1791,
    lon: -94.3235,
    address: "800 W Central Ave, Carthage, MO",
    cuisines: ["cafe", "coffee", "breakfast", "brunch"],
    cuisineLabel: "Coffee / Crepes",
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 13,
    openingHours: "Mo-Fr 06:00-14:00; Sa 07:00-13:00; Su off",
    phone: "+1 417-612-4736",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["mother road coffee"],
    id: "local-mother-road-carthage",
    name: "Mother Road Coffee",
    lat: 37.17655,
    lon: -94.31139,
    address: "325 S Main St, Carthage, MO",
    cuisines: ["cafe", "coffee", "breakfast", "sandwiches"],
    cuisineLabel: "Coffee / Cafe",
    priceLevel: 1,
    rating: 4.8,
    reviewCount: 84,
    openingHours: "Mo-Th 07:00-17:00; Fr 06:30-17:00; Sa 07:30-15:00; Su off",
    phone: "+1 417-359-8182",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["bamboo garden", "bamboo gardens"],
    id: "local-bamboo-garden-carthage",
    name: "Bamboo Garden",
    lat: 37.1794,
    lon: -94.3142,
    address: "102 N Garrison Ave, Carthage, MO",
    cuisines: ["chinese", "international"],
    cuisineLabel: "Chinese",
    priceLevel: 1,
    rating: 4.0,
    reviewCount: 72,
    openingHours: "Mo-Su 11:00-21:00",
    phone: "+1 417-358-1611",
    isChain: false,
    photoKey: "asian",
  },
  {
    matchNames: ["pancake hut"],
    id: "local-pancake-hut-carthage",
    name: "Pancake Hut",
    lat: 37.17655,
    lon: -94.3142,
    address: "301 S Garrison Ave, Carthage, MO",
    cuisines: ["breakfast", "american", "southern"],
    cuisineLabel: "Breakfast / Diner",
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 203,
    openingHours: "Mo-Su 05:30-13:30",
    phone: "+1 417-358-8481",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["the carthage deli", "carthage deli"],
    id: "local-carthage-deli",
    name: "The Carthage Deli",
    lat: 37.17675,
    lon: -94.31139,
    address: "301 S Main St, Carthage, MO",
    cuisines: ["deli", "sandwiches", "american", "breakfast"],
    cuisineLabel: "Deli / Sandwiches",
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 37,
    openingHours: "Mo-Fr 07:05-17:00; Sa 07:05-15:00; Su off",
    phone: "+1 417-358-8820",
    website: "https://carthagedeli.com/",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["big ben's bbq station", "big bens bbq station", "big ben's bbq"],
    id: "local-big-bens-carthage",
    name: "Big Ben's BBQ Station",
    lat: 37.149,
    lon: -94.305,
    address: "2817 The Loop, Carthage, MO",
    cuisines: ["bbq", "american"],
    cuisineLabel: "BBQ",
    priceLevel: 2,
    rating: 0,
    reviewCount: 308,
    openingHours: "Mo-Th 11:00-20:00; Fr-Sa 11:00-20:30; Su 11:00-14:30",
    phone: "+1 417-237-0752",
    isChain: false,
    photoKey: "bbq",
  },
];
