import type { CuisineId, PhotoKey, PriceLevel, Restaurant } from "./types";

export interface CatalogEntry {
  matchNames: string[];
  id: string;
  name: string;
  lat: number;
  lon: number;
  address: string;
  cuisines: CuisineId[];
  cuisineLabel: string;
  priceLevel: PriceLevel;
  rating: number;
  reviewCount: number;
  openingHours: string;
  phone?: string;
  website?: string;
  isChain: boolean;
  photoKey: PhotoKey;
}

export const LOCAL_CATALOG: CatalogEntry[] = [
  {
    matchNames: ["the bruncheonette", "bruncheonette"],
    id: "local-bruncheonette",
    name: "The Bruncheonette",
    lat: 37.094422,
    lon: -94.513136,
    address: "424 N Main St, Joplin, MO",
    cuisines: ["breakfast", "brunch", "sandwiches", "cafe"],
    cuisineLabel: "Breakfast / Brunch",
    priceLevel: 1,
    rating: 4.7,
    reviewCount: 280,
    openingHours: "Mo-Sa 07:00-14:00; Su 08:00-14:00",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["mythos", "mythos euro greek kuzina"],
    id: "local-mythos",
    name: "Mythos",
    lat: 37.076145,
    lon: -94.477717,
    address: "1306 S Range Line Rd, Joplin, MO",
    cuisines: ["greek", "mediterranean", "steakhouse"],
    cuisineLabel: "Greek / Mediterranean",
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 210,
    openingHours: "Su-Th 11:00-21:00; Fr-Sa 11:00-22:00",
    isChain: false,
    photoKey: "mediterranean",
  },
  {
    matchNames: ["wilder's steakhouse", "wilders steakhouse", "wilder's"],
    id: "local-wilders",
    name: "Wilder's Steakhouse",
    lat: 37.077795,
    lon: -94.513875,
    address: "1216 S Main St, Joplin, MO",
    cuisines: ["steakhouse", "american", "seafood"],
    cuisineLabel: "Steakhouse",
    priceLevel: 3,
    rating: 4.4,
    reviewCount: 154,
    openingHours: "Mo-Th 16:30-21:00; Fr-Sa 16:30-22:00; Su 16:30-20:00",
    isChain: false,
    photoKey: "steak",
  },
  {
    matchNames: ["thai time", "thai time cafe"],
    id: "local-thai-time",
    name: "Thai Time Cafe",
    lat: 37.054724,
    lon: -94.492788,
    address: "1804 E 32nd St, Joplin, MO",
    cuisines: ["thai", "international"],
    cuisineLabel: "Thai",
    priceLevel: 2,
    rating: 4.4,
    reviewCount: 251,
    openingHours: "Mo-Sa 11:00-21:00; Su 12:00-20:00",
    isChain: false,
    photoKey: "thai",
  },
  {
    matchNames: ["crabby", "crabby's", "crabbys", "crabby's seafood"],
    id: "local-crabbys",
    name: "Crabby's",
    lat: 37.055481,
    lon: -94.53572,
    address: "1801 W 32nd St, Joplin, MO",
    cuisines: ["seafood", "american"],
    cuisineLabel: "Seafood",
    priceLevel: 3,
    rating: 4.2,
    reviewCount: 239,
    openingHours: "Mo-Th 16:00-21:00; Fr-Sa 16:00-22:00; Su 16:00-20:00",
    isChain: false,
    photoKey: "seafood",
  },
  {
    matchNames: ["blackstone gastropub", "blackstone"],
    id: "local-blackstone",
    name: "Blackstone Gastropub",
    lat: 37.091899,
    lon: -94.506276,
    address: "1521 E Broadway St, Joplin, MO",
    cuisines: ["american", "burgers"],
    cuisineLabel: "American",
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 157,
    openingHours: "Mo-Th 11:00-21:00; Fr-Sa 11:00-22:00; Su 11:00-21:00",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["red onion cafe", "red onion"],
    id: "local-red-onion",
    name: "Red Onion Cafe",
    lat: 37.087765,
    lon: -94.512057,
    address: "203 E 4th St, Joplin, MO",
    cuisines: ["american", "cafe", "sandwiches"],
    cuisineLabel: "American / Casual",
    priceLevel: 2,
    rating: 4.6,
    reviewCount: 317,
    openingHours: "Mo-Sa 11:00-21:00; Su 11:00-15:00",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["latin fusion"],
    id: "local-latin-fusion",
    name: "Latin Fusion",
    lat: 37.074792,
    lon: -94.514006,
    address: "1520 S Main St, Joplin, MO",
    cuisines: ["mexican", "international"],
    cuisineLabel: "Mexican / Honduran",
    priceLevel: 2,
    rating: 4.9,
    reviewCount: 120,
    openingHours: "Mo-Sa 11:00-21:00; Su 11:00-20:00",
    isChain: false,
    photoKey: "mexican",
  },
  {
    matchNames: ["sakura sushi", "sakura sushi & grill", "sakura"],
    id: "local-sakura",
    name: "Sakura Sushi & Grill",
    lat: 37.055318,
    lon: -94.535901,
    address: "1802 W 32nd St, Joplin, MO",
    cuisines: ["sushi", "japanese", "steakhouse"],
    cuisineLabel: "Sushi / Japanese",
    priceLevel: 2,
    rating: 4.3,
    reviewCount: 127,
    openingHours: "Mo-Th 11:00-21:00; Fr-Sa 11:00-22:00; Su 11:00-21:00",
    isChain: false,
    photoKey: "asian",
  },
  {
    matchNames: ["club 609"],
    id: "local-club-609",
    name: "Club 609",
    lat: 37.085091,
    lon: -94.513224,
    address: "609 S Main St, Joplin, MO",
    cuisines: ["american", "sandwiches"],
    cuisineLabel: "American",
    priceLevel: 2,
    rating: 4.3,
    reviewCount: 90,
    openingHours: "Mo-Sa 11:00-22:00; Su 11:00-21:00",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["club 1201"],
    id: "local-club-1201",
    name: "Club 1201",
    lat: 37.078207,
    lon: -94.513652,
    address: "1201 S Main St, Joplin, MO",
    cuisines: ["american", "brunch"],
    cuisineLabel: "American",
    priceLevel: 2,
    rating: 4.2,
    reviewCount: 80,
    openingHours: "Mo-Th 11:00-21:00; Fr-Sa 11:00-22:00; Su 10:00-20:00",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["fred and red", "fred & red's", "fred & reds"],
    id: "local-fred-reds",
    name: "Fred & Red's",
    lat: 37.0728,
    lon: -94.51414,
    address: "1719 S Main St, Joplin, MO",
    cuisines: ["american", "sandwiches"],
    cuisineLabel: "American",
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 88,
    openingHours: "Mo-Sa 10:30-20:00; Su off",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["finn's", "finns"],
    id: "local-finns",
    name: "Finn's",
    lat: 37.079971,
    lon: -94.477349,
    address: "1031 S Range Line Rd, Joplin, MO",
    cuisines: ["american", "seafood"],
    cuisineLabel: "American",
    priceLevel: 2,
    rating: 4.3,
    reviewCount: 164,
    openingHours: "Mo-Th 11:00-21:00; Fr-Sa 11:00-22:00; Su 11:00-20:00",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["hungry monkey"],
    id: "local-hungry-monkey",
    name: "Hungry Monkey",
    lat: 37.086307,
    lon: -94.513498,
    address: "528 S Main St, Joplin, MO",
    cuisines: ["healthy", "seafood", "international"],
    cuisineLabel: "Healthy / Poke",
    priceLevel: 2,
    rating: 4.7,
    reviewCount: 50,
    openingHours: "Mo-Sa 11:00-19:00; Su 12:00-17:00",
    isChain: false,
    photoKey: "seafood",
  },
  {
    matchNames: ["kinnaree", "kinnaree thai"],
    id: "local-kinnaree",
    name: "Kinnaree",
    lat: 37.083861,
    lon: -94.485545,
    address: "2623 E 7th St, Joplin, MO",
    cuisines: ["thai"],
    cuisineLabel: "Thai",
    priceLevel: 2,
    rating: 4.3,
    reviewCount: 70,
    openingHours: "Mo-Sa 11:00-21:00; Su 12:00-20:00",
    isChain: false,
    photoKey: "thai",
  },
  {
    matchNames: ["magic noodle"],
    id: "local-magic-noodle",
    name: "Magic Noodle",
    lat: 37.0837,
    lon: -94.486055,
    address: "2600 E 7th St, Joplin, MO",
    cuisines: ["thai", "chinese"],
    cuisineLabel: "Thai / Noodles",
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 60,
    openingHours: "Mo-Sa 11:00-21:00; Su 12:00-20:00",
    isChain: false,
    photoKey: "thai",
  },
  {
    matchNames: ["bricktown brewery", "bricktown"],
    id: "local-bricktown",
    name: "Bricktown Brewery",
    lat: 37.056856,
    lon: -94.478929,
    address: "2600 S Range Line Rd, Joplin, MO",
    cuisines: ["american", "burgers"],
    cuisineLabel: "American",
    priceLevel: 2,
    rating: 4.4,
    reviewCount: 131,
    openingHours: "Su-Th 11:00-22:00; Fr-Sa 11:00-23:00",
    isChain: true,
    photoKey: "american",
  },
  {
    matchNames: ["hackett hot wings", "hackett's hot wings"],
    id: "local-hackett",
    name: "Hackett Hot Wings",
    lat: 37.086032,
    lon: -94.51369,
    address: "520 S Main St, Joplin, MO",
    cuisines: ["wings", "chicken", "american"],
    cuisineLabel: "Wings",
    priceLevel: 2,
    rating: 4.1,
    reviewCount: 140,
    openingHours: "Mo-Th 11:00-21:00; Fr-Sa 11:00-22:00; Su 12:00-20:00",
    website: "https://hacketthotwings.com/",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["woody's wood fired pizza", "woody's woodfire pizza", "woodys wood fired pizza"],
    id: "local-woodys",
    name: "Woody's Wood Fired Pizza",
    lat: 37.084976,
    lon: -94.537653,
    address: "3316 Adele Ave, Joplin, MO",
    cuisines: ["pizza", "italian"],
    cuisineLabel: "Pizza",
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 96,
    openingHours: "Mo-Th 11:00-21:00; Fr-Sa 11:00-22:00; Su 12:00-20:00",
    isChain: false,
    photoKey: "pizza",
  },
  {
    matchNames: ["first watch"],
    id: "local-first-watch",
    name: "First Watch",
    lat: 37.054122,
    lon: -94.477853,
    address: "3231 S Range Line Rd, Joplin, MO",
    cuisines: ["breakfast", "brunch", "cafe", "american"],
    cuisineLabel: "Breakfast / Brunch",
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 129,
    openingHours: "Mo-Su 07:00-14:30",
    isChain: true,
    photoKey: "cafe",
  },
  {
    matchNames: ["tokyo japanese steakhouse", "tokyo"],
    id: "local-tokyo",
    name: "Tokyo Japanese Steakhouse",
    lat: 37.095447,
    lon: -94.476314,
    address: "511 N Range Line Rd, Joplin, MO",
    cuisines: ["japanese", "steakhouse", "sushi"],
    cuisineLabel: "Japanese / Steakhouse",
    priceLevel: 3,
    rating: 4.2,
    reviewCount: 100,
    openingHours: "Mo-Th 11:00-22:00; Fr-Sa 11:00-23:00; Su 11:00-21:00",
    isChain: false,
    photoKey: "asian",
  },
  {
    matchNames: ["lalo's taqueria", "lalos taqueria"],
    id: "local-lalos",
    name: "Lalo's Taqueria",
    lat: 37.084326,
    lon: -94.520728,
    address: "733 W 7th St, Joplin, MO",
    cuisines: ["mexican"],
    cuisineLabel: "Mexican",
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 70,
    openingHours: "Mo-Sa 10:00-21:00; Su 10:00-20:00",
    isChain: false,
    photoKey: "mexican",
  },
  {
    matchNames: ["norma's diner", "normas diner"],
    id: "local-normas",
    name: "Norma's Diner",
    lat: 37.08369,
    lon: -94.513407,
    address: "723 S Main St, Joplin, MO",
    cuisines: ["american", "breakfast", "southern"],
    cuisineLabel: "American / Diner",
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 42,
    openingHours: "Mo-Sa 06:00-14:00; Su 07:00-14:00",
    isChain: false,
    photoKey: "cafe",
  },
  {
    matchNames: ["dude's daylight donut", "dudes daylight donut"],
    id: "local-dudes",
    name: "Dude's Daylight Donut Shop",
    lat: 37.071732,
    lon: -94.514142,
    address: "1802 S Main St, Joplin, MO",
    cuisines: ["bakery", "dessert", "breakfast", "coffee"],
    cuisineLabel: "Bakery / Donuts",
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 38,
    openingHours: "Mo-Sa 05:00-13:00; Su 05:00-12:00",
    isChain: false,
    photoKey: "dessert",
  },
  {
    matchNames: ["stogey's", "stogeys", "stogey's coney island"],
    id: "local-stogeys",
    name: "Stogey's Coney Island",
    lat: 37.083893,
    lon: -94.490343,
    address: "2207 E 7th St, Joplin, MO",
    cuisines: ["american", "sandwiches"],
    cuisineLabel: "American",
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 51,
    openingHours: "Mo-Sa 10:30-20:00; Su 11:00-18:00",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["habaneros mexican grill", "habaneros"],
    id: "local-habaneros-joplin",
    name: "Habaneros Mexican Grill",
    lat: 37.08386,
    lon: -94.4872,
    address: "2526 E 7th St, Joplin, MO",
    cuisines: ["mexican"],
    cuisineLabel: "Mexican",
    priceLevel: 2,
    rating: 4.3,
    reviewCount: 200,
    openingHours: "Mo-Su 11:00-21:00",
    isChain: false,
    photoKey: "mexican",
  },
];

export function catalogToRestaurant(entry: CatalogEntry): Restaurant {
  return {
    id: entry.id,
    name: entry.name,
    lat: entry.lat,
    lon: entry.lon,
    address: entry.address,
    cuisines: entry.cuisines,
    cuisineLabel: entry.cuisineLabel,
    priceLevel: entry.priceLevel,
    rating: entry.rating,
    reviewCount: entry.reviewCount,
    openingHours: entry.openingHours,
    phone: entry.phone ?? null,
    website: entry.website ?? null,
    isChain: entry.isChain,
    photoKey: entry.photoKey,
    source: "catalog",
  };
}
