import type { CatalogEntry } from "./catalog";

// Jasper County expansion, audited September 2026.
// This layer supplements live OpenStreetMap discovery. Entries are only added
// when the business location is precise enough to support distance filtering
// and directions without guessing.
export const JASPER_COUNTY_LOCAL_CATALOG: CatalogEntry[] = [
  // Webb City
  {
    matchNames: ["pho-4-ever", "pho 4 ever", "pho4ever"],
    id: "local-pho-4-ever-webb-city",
    name: "PHO-4-EVER",
    lat: 37.1383291,
    lon: -94.4743508,
    address: "701 S Madison St, Webb City, MO",
    cuisines: ["international", "other"],
    cuisineLabel: "Vietnamese / Pho",
    priceLevel: 2,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo-Sa 11:00-20:00; Su off",
    phone: "+1 417-717-0165",
    website: "https://pho4everwc.com/",
    isChain: false,
    photoKey: "asian",
  },
  {
    matchNames: ["flat creek webb city", "flat creek", "flat creek restaurant"],
    id: "local-flat-creek-webb-city",
    name: "Flat Creek Webb City",
    lat: 37.1439465,
    lon: -94.4567124,
    address: "215 S East St, Webb City, MO",
    cuisines: ["american", "seafood", "chicken"],
    cuisineLabel: "American / Seafood",
    priceLevel: 2,
    rating: 0,
    reviewCount: 0,
    openingHours: "Su-Th 10:30-21:00; Fr-Sa 10:30-22:00",
    isChain: false,
    photoKey: "american",
  },
  {
    matchNames: ["flag city brewing", "flag city brewery"],
    id: "local-flag-city-brewing",
    name: "Flag City Brewing",
    lat: 37.1416,
    lon: -94.4698,
    address: "618 W 4th St, Webb City, MO",
    cuisines: ["american", "other"],
    cuisineLabel: "Brewery / Taproom",
    priceLevel: 2,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo-Tu off; We-Th 16:00-22:00; Fr-Sa 14:00-22:00; Su off",
    phone: "+1 417-437-0164",
    isChain: false,
    photoKey: "american",
  },

  // Carl Junction
  {
    matchNames: ["aussie's", "aussies", "joe's 19th hole", "joes 19th hole"],
    id: "local-aussies-carl-junction",
    name: "Aussie's",
    lat: 37.159756,
    lon: -94.539375,
    address: "502 Briarbrook Dr, Carl Junction, MO",
    cuisines: ["american", "burgers"],
    cuisineLabel: "American / Sports Bar",
    priceLevel: 2,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo-Tu 11:00-21:00; We-Th 11:00-22:00; Fr 11:00-01:00; Sa 09:00-01:00; Su 09:00-21:00",
    isChain: false,
    photoKey: "american",
  },

  // Sarcoxie
  {
    matchNames: ["golden plate", "golden plate restaurant"],
    id: "local-golden-plate-sarcoxie",
    name: "Golden Plate",
    lat: 37.07103,
    lon: -94.12601,
    address: "1324 High St, Sarcoxie, MO",
    cuisines: ["chinese", "international"],
    cuisineLabel: "Chinese",
    priceLevel: 1,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo-Sa 11:00-20:00; Su off",
    isChain: false,
    photoKey: "asian",
  },
  {
    matchNames: ["sarcoxie red front", "red front", "red front coffee"],
    id: "local-red-front-sarcoxie",
    name: "Sarcoxie Red Front",
    lat: 37.0688,
    lon: -94.1165,
    address: "508 Center St, Sarcoxie, MO",
    cuisines: ["cafe", "coffee"],
    cuisineLabel: "Coffee / Cafe",
    priceLevel: 1,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo-Fr 07:00-17:00; Sa 07:00-12:00; Su off",
    phone: "+1 417-548-2736",
    isChain: false,
    photoKey: "cafe",
  },

  // Jasper
  {
    matchNames: ["mckay's dari creme", "mckays dari creme", "mckay's", "mckays"],
    id: "local-mckays-jasper",
    name: "McKay's Dari Creme",
    lat: 37.3141,
    lon: -94.3347,
    address: "200 S 4th St, Jasper, MO",
    cuisines: ["american", "burgers", "ice_cream"],
    cuisineLabel: "Burgers / Ice Cream",
    priceLevel: 1,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo-Sa 11:00-20:00; Su off",
    phone: "+1 417-394-2954",
    isChain: false,
    photoKey: "american",
  },

  // Carterville
  {
    matchNames: ["dead cow saloon and grill", "dead cow saloon & grill", "dead cow saloon"],
    id: "local-dead-cow-carterville",
    name: "Dead Cow Saloon and Grill",
    lat: 37.149215,
    lon: -94.438933,
    address: "328 E Main St, Carterville, MO",
    cuisines: ["american", "bbq", "burgers"],
    cuisineLabel: "Bar & Grill / BBQ",
    priceLevel: 2,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo-Th 11:00-23:00; Fr-Sa 11:00-24:00; Su 10:00-24:00",
    phone: "+1 417-673-2833",
    isChain: false,
    photoKey: "bbq",
  },

  // Alba
  {
    matchNames: ["beard engine brewing", "beard engine brewing co", "beard engine"],
    id: "local-beard-engine-alba",
    name: "Beard Engine Brewing Co.",
    lat: 37.2382073,
    lon: -94.4179577,
    address: "208 Main St, Alba, MO",
    cuisines: ["other"],
    cuisineLabel: "Brewery / Taproom",
    priceLevel: 2,
    rating: 0,
    reviewCount: 0,
    openingHours: "Mo-Th off; Fr 14:00-22:00; Sa 12:00-20:00; Su 13:00-18:00",
    phone: "+1 417-525-4900",
    website: "https://www.beardenginebrewco.com/",
    isChain: false,
    photoKey: "american",
  },
];

export const JASPER_COUNTY_AUDIT = {
  auditedAt: "2026-09",
  incorporatedPlaces: [
    "Airport Drive",
    "Alba",
    "Asbury",
    "Avilla",
    "Brooklyn Heights",
    "Carl Junction",
    "Carterville",
    "Carthage",
    "Carytown",
    "Duenweg",
    "Duquesne",
    "Fidelity",
    "Jasper",
    "Joplin",
    "La Russell",
    "Neck City",
    "Oronogo",
    "Purcell",
    "Reeds",
    "Sarcoxie",
    "Waco",
    "Webb City",
  ],
  // Places without a verified curated record intentionally continue to rely on
  // live discovery rather than receiving approximate or invented coordinates.
  strategy: "live-plus-curated" as const,
};
