import type { CasinoAuditRecord } from "./casino-catalog";

const VERIFIED_ON = "2026-09-11";
const casino=(id:string,name:string,lat:number,lon:number,address:string,operator:string,website:string,identitySource:string,notes:string):CasinoAuditRecord=>({id:`casino-catalog-${id}`,name,lat,lon,address,cuisines:["other"],cuisineLabel:"Casino",priceLevel:null,rating:null,reviewCount:null,openingHours:null,phone:null,website,isChain:false,photoKey:"cafe",source:"catalog",venueTypes:["casino"],energyLevel:2,audit:{verifiedOn:VERIFIED_ON,jurisdiction:"Colorado",operator,identitySource,notes}});
const NOTE="Current Colorado destination cleared statewide consumer-destination, address, property-coordinate, stable-ID and duplicate/alias QA on September 11, 2026.";

/** Colorado Pass 29: 31 reconciled current casino destinations. */
export const CASINO_CATALOG_PASS_29: CasinoAuditRecord[] = [
  casino("co-black-hawk-ameristar","Ameristar Casino Resort Spa Black Hawk",39.80015,-105.48935,"111 Richman Street, Black Hawk, CO 80422","Ameristar Black Hawk","https://www.ameristarblackhawk.com/","https://www.ameristarblackhawk.com/casino",NOTE),
  casino("co-black-hawk-horseshoe","Horseshoe Black Hawk",39.7980972,-105.4834834,"401 Main Street, Black Hawk, CO 80422","Horseshoe Black Hawk","https://www.caesars.com/horseshoe-black-hawk","https://www.caesars.com/horseshoe-black-hawk",NOTE),
  casino("co-black-hawk-lady-luck","Lady Luck Casino Black Hawk",39.79877,-105.48655,"340 Main Street, Black Hawk, CO 80422","Lady Luck Black Hawk","https://www.caesars.com/lady-luck-black-hawk","https://www.caesars.com/lady-luck-black-hawk",NOTE),
  casino("co-black-hawk-lodge","The Lodge Casino",39.79967,-105.49008,"240 Main Street, Black Hawk, CO 80422","The Lodge Casino","https://thelodgecasino.com/","https://thelodgecasino.com/contact-us/",NOTE),
  casino("co-black-hawk-gilpin","The Gilpin Casino",39.80084,-105.49301,"111 Main Street, Black Hawk, CO 80422","The Gilpin Casino","https://thegilpincasino.com/","https://thegilpincasino.com/contact-us/",NOTE),
  casino("co-black-hawk-monarch","Monarch Casino Resort Spa Black Hawk",39.79860,-105.48341,"488 Main Street, Black Hawk, CO 80422","Monarch Black Hawk","https://monarchblackhawk.com/","https://monarchblackhawk.com/contact-us",NOTE),
  casino("co-black-hawk-saratoga","Saratoga Casino Black Hawk",39.80134,-105.49411,"101 Main Street, Black Hawk, CO 80422","Saratoga Casino Black Hawk","https://www.saratogacasinobh.com/","https://www.saratogacasinobh.com/visit",NOTE),
  casino("co-black-hawk-sasquatch","Sasquatch Casino",39.80184,-105.49444,"125 Gregory Street, Black Hawk, CO 80422","Sasquatch Casino","https://sasquatchcasino.com/","https://sasquatchcasino.com/contact-us/",NOTE),
  casino("co-black-hawk-wild-card","Wild Card Saloon",39.801582,-105.493541,"120 Main Street, Black Hawk, CO 80422","Wild Card Saloon","https://wildcardsaloon.com/","https://wildcardsaloon.com/contact-us/",NOTE),
  casino("co-black-hawk-bigfoot","Bigfoot Casino",39.8018751,-105.4945333,"101 Gregory Street, Black Hawk, CO 80422","Bigfoot Casino","https://bigfootcasinoblackhawk.com/","https://bigfootcasinoblackhawk.com/",`${NOTE} Current successor at the former Z Casino property; obsolete Z branding is not emitted separately.`),
  casino("co-black-hawk-ballys-east","Bally's Black Hawk East",39.79845,-105.48767,"321 Main Street, Black Hawk, CO 80422","Bally's Black Hawk","https://casinos.ballys.com/black-hawk/","https://casinos.ballys.com/black-hawk/contact-us.htm",`${NOTE} Retained as a separately routable physical subproperty.`),
  casino("co-black-hawk-ballys-north","Bally's Black Hawk North",39.79894,-105.48825,"300 Main Street, Black Hawk, CO 80422","Bally's Black Hawk","https://casinos.ballys.com/black-hawk/","https://casinos.ballys.com/black-hawk/contact-us.htm",`${NOTE} Retained as a separately routable physical subproperty.`),
  casino("co-black-hawk-ballys-west","Bally's Black Hawk West",39.79883,-105.48885,"261 Main Street, Black Hawk, CO 80422","Bally's Black Hawk","https://casinos.ballys.com/black-hawk/","https://casinos.ballys.com/black-hawk/contact-us.htm",`${NOTE} Retained as a separately routable physical subproperty.`),
  casino("co-central-city-century","Century Casino & Hotel Central City",39.800474,-105.512168,"102 Main Street, Central City, CO 80427","Century Casino Central City","https://www.cnty.com/central-city/","https://www.cnty.com/central-city/",NOTE),
  casino("co-central-city-dostal-alley","Dostal Alley Casino & Brew Pub",39.8002,-105.51244,"116 Main Street, Central City, CO 80427","Dostal Alley Casino","https://dostalalley.com/","https://www.visitcentralcity.com/explore",NOTE),
  casino("co-central-city-easy-street","Easy Street Casino",39.7998967,-105.5124236,"120 Main Street, Central City, CO 80427","Easy Street Casino","https://easystreetcentralcity.com/","https://easystreetcentralcity.com/contact-us/",NOTE),
  casino("co-central-city-famous-bonanza","The Famous Bonanza Casino",39.8005673,-105.5129721,"107 Main Street, Central City, CO 80427","Famous Bonanza Casino","https://famousbonanza.com/","https://famousbonanza.com/",NOTE),
  casino("co-central-city-dragon-tiger","Dragon Tiger Casino",39.80085,-105.51127,"132 Lawrence Street, Central City, CO 80427","Dragon Tiger Casino","https://dragontigercasinos.com/","https://dragontigercasinos.com/",NOTE),
  casino("co-central-city-grand-z","Grand Z Casino & Hotel",39.79999,-105.50924,"321 Gregory Street, Central City, CO 80427","Grand Z Casino Hotel","https://grandzcasinohotel.com/","https://grandzcasinohotel.com/",NOTE),
  casino("co-cripple-creek-bronco-billys","Bronco Billy's Casino",38.7469187,-105.1773835,"233 E Bennett Ave, Cripple Creek, CO 80813","Bronco Billy's Casino","https://chamonixco.com/bronco-billys-casino/","https://chamonixco.com/bronco-billys-casino/",`${NOTE} Separately routable from adjoining Chamonix.`),
  casino("co-cripple-creek-chamonix","Chamonix Casino Hotel",38.74678,-105.17815,"201 E Bennett Ave, Cripple Creek, CO 80813","Chamonix Casino Hotel","https://chamonixco.com/","https://chamonixco.com/",`${NOTE} Separately routable from adjoining Bronco Billy's.`),
  casino("co-cripple-creek-century","Century Casino & Hotel Cripple Creek",38.746535,-105.17802,"200-220 E Bennett Ave, Cripple Creek, CO 80813","Century Casino Cripple Creek","https://www.cnty.com/cripple-creek/","https://www.cnty.com/cripple-creek/",`${NOTE} Multiple regulator rows collapse to this one consumer property.`),
  casino("co-cripple-creek-colorado-grande","Colorado Grande Casino & Hotel",38.7465306,-105.1761483,"300 E Bennett Ave, Cripple Creek, CO 80813","Colorado Grande Casino","https://cogrande.com/","https://cogrande.com/",NOTE),
  casino("co-cripple-creek-johnny-nolons","Johnny Nolon's Casino",38.74684,-105.17619,"301 E Bennett Ave, Cripple Creek, CO 80813","Johnny Nolon's Casino","https://johnnynolonscasino.com/","https://johnnynolonscasino.com/",NOTE),
  casino("co-cripple-creek-midnight-rose","Midnight Rose Hotel & Casino",38.74639,-105.17691,"256 E Bennett Ave, Cripple Creek, CO 80813","Triple Crown Casinos","https://www.triplecrowncasinos.com/","https://www.triplecrowncasinos.com/contact/",NOTE),
  casino("co-cripple-creek-mcgills","McGills Hotel and Casino",38.7465374,-105.1774336,"232 E Bennett Ave, Cripple Creek, CO 80813","Triple Crown Casinos","https://www.triplecrowncasinos.com/","https://www.triplecrowncasinos.com/contact/",NOTE),
  casino("co-cripple-creek-brass-ass","The Brass Ass Casino",38.7465484,-105.1764874,"264 E Bennett Ave, Cripple Creek, CO 80813","Triple Crown Casinos","https://www.triplecrowncasinos.com/","https://www.triplecrowncasinos.com/contact/",NOTE),
  casino("co-cripple-creek-double-eagle","Double Eagle Hotel & Casino",38.74653,-105.17336,"442 E Bennett Ave, Cripple Creek, CO 80813","Double Eagle Hotel & Casino","https://www.decasino.com/","https://www.decasino.com/contact/",NOTE),
  casino("co-cripple-creek-golden-nugget","Golden Nugget Cripple Creek",38.75031,-105.17353,"119 Carbonate Street, Cripple Creek, CO 80813","Golden Nugget Cripple Creek","https://www.goldennugget.com/cripple-creek/","https://www.goldennugget.com/cripple-creek/contact-us/",`${NOTE} Current successor at the former Wildwood casino property; adjacent hotel is not a separate casino destination.`),
  casino("co-sky-ute-casino-resort","Sky Ute Casino Resort",37.138214,-107.6323312,"14324 US Highway 172 North, Ignacio, CO 81137","Southern Ute Indian Tribe","https://www.skyutecasino.com/","https://www.skyutecasino.com/",NOTE),
  casino("co-ute-mountain-casino","Ute Mountain Casino Hotel",37.20475,-108.68612,"3 Weeminuche Drive, Towaoc, CO 81334","Ute Mountain Ute Tribe","https://utemountaincasino.com/","https://utemountaincasino.com/contact-us/",NOTE),
];
