import type { NightlifePlace } from "./types";

// Curated September 2026 nightlife safety net for the Joplin/Carthage area.
// The live OSM query is still preferred and merged with these records.
export const LOCAL_NIGHTLIFE_CATALOG: NightlifePlace[] = [
  {
    id: "nightlife-122-lounge",
    name: "The 122 Lounge",
    lat: 37.09005,
    lon: -94.51352,
    address: "122A S Main St, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Cocktail Lounge",
    priceLevel: 2,
    rating: 5,
    reviewCount: 21,
    openingHours: "Mo-Tu off; We-Sa 16:00-24:00; Su off",
    phone: "+1 417-850-1541",
    website: "https://the122lounge.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    venueTypes: ["lounge", "bar"],
    energyLevel: 1,
  },
  {
    id: "nightlife-blackthorn",
    name: "Blackthorn Pizza & Pub",
    lat: 37.08645,
    lon: -94.51463,
    address: "510 S Joplin Ave, Joplin, MO",
    cuisines: ["pizza", "american"],
    cuisineLabel: "Pub / Live Music",
    priceLevel: 2,
    rating: 3.9,
    reviewCount: 32,
    openingHours: "Mo-Th 11:00-24:00; Fr-Sa 11:00-01:30; Su 11:00-24:00",
    phone: "+1 417-623-2485",
    isChain: false,
    photoKey: "pizza",
    source: "catalog",
    venueTypes: ["pub", "bar", "club"],
    energyLevel: 3,
  },
  {
    id: "nightlife-brew-pub-parlor",
    name: "Brew Pub & Parlor",
    lat: 37.08245,
    lon: -94.51355,
    address: "813 S Main St, Joplin, MO",
    cuisines: ["american", "pizza"],
    cuisineLabel: "Pub / Billiards",
    priceLevel: 1,
    rating: 3,
    reviewCount: 2,
    openingHours: "Mo 19:00-01:30; Tu-Th 11:00-01:30; Fr-Sa 11:00-01:30; Su 19:00-01:30",
    phone: "+1 417-629-4940",
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["pub", "bar"],
    energyLevel: 2,
  },
  {
    id: "nightlife-chaos-brewing",
    name: "Chaos Brewing",
    lat: 37.090181,
    lon: -94.513523,
    address: "112 S Main St, Joplin, MO",
    cuisines: ["pizza", "american"],
    cuisineLabel: "Brewery / Taproom",
    priceLevel: 2,
    rating: 5,
    reviewCount: 96,
    openingHours: "Mo-Tu off; We-Th 17:00-22:00; Fr 15:00-22:00; Sa 12:00-22:00; Su 12:00-18:00",
    phone: "+1 417-553-4007",
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["brewery", "bar"],
    energyLevel: 1,
  },
  {
    id: "nightlife-whiskey-dicks",
    name: "Whiskey Dick's",
    lat: 37.0863,
    lon: -94.51463,
    address: "516 S Joplin Ave, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Dive Bar / Karaoke",
    priceLevel: 1,
    rating: 3.9,
    reviewCount: 18,
    openingHours: "Mo-Sa 17:00-01:30; Su off",
    phone: "+1 417-206-3425",
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["bar", "club"],
    energyLevel: 3,
  },
  {
    id: "nightlife-starry-eyed-girl",
    name: "Starry Eyed Girl",
    lat: 37.0864,
    lon: -94.5115,
    address: "512 S Virginia Ave, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Wine Bar / Lounge",
    priceLevel: 2,
    rating: 4.9,
    reviewCount: 18,
    openingHours: "Su-Mo off; Tu-Th 16:00-21:00; Fr-Sa 16:00-22:00",
    phone: "+1 417-279-5591",
    website: "https://www.starryeyedgirljoplin.com/",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    venueTypes: ["lounge", "bar"],
    energyLevel: 1,
  },
  {
    id: "nightlife-vino-noir",
    name: "Vino Noir Wine Bar",
    lat: 37.0858,
    lon: -94.5137,
    address: "530 S Main St, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Wine Bar",
    priceLevel: 2,
    rating: null,
    reviewCount: null,
    openingHours: "Mo-We off; Th 17:00-22:00; Fr-Sa 17:00-23:00; Su off",
    phone: "+1 417-499-3912",
    website: "https://www.christinesvineyard.com/vino-noir-winebar",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    venueTypes: ["lounge", "bar"],
    energyLevel: 1,
  },
  {
    id: "nightlife-old-broadway",
    name: "Old Broadway Club",
    lat: 37.091625,
    lon: -94.505774,
    address: "702 Broadway St, Joplin, MO",
    cuisines: ["american", "burgers"],
    cuisineLabel: "Bar / Pub",
    priceLevel: 1,
    rating: null,
    reviewCount: null,
    openingHours: "Mo off; Tu-Sa 11:00-01:30; Su off",
    phone: "+1 417-621-0601",
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["bar", "pub"],
    energyLevel: 2,
  },
  {
    id: "nightlife-guitars",
    name: "Guitars Rock N' Country Bar",
    lat: 37.0842,
    lon: -94.538,
    address: "1800 W 7th St, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Country Bar / Dance Club",
    priceLevel: 1,
    rating: 3.5,
    reviewCount: 89,
    openingHours: "Su-Th off; Fr-Sa 19:00-01:15",
    phone: "+1 417-782-6444",
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["club", "bar"],
    energyLevel: 3,
  },
  {
    id: "nightlife-rumors",
    name: "Rumors Cocktail Lounge",
    lat: 37.0842,
    lon: -94.5385,
    address: "1825 W 7th St, Suite 3, Joplin, MO",
    cuisines: ["other"],
    cuisineLabel: "Cocktail Lounge / Karaoke",
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 77,
    openingHours: "Mo-Th 11:00-23:00; Fr-Sa 11:00-01:30; Su 11:00-19:00",
    phone: "+1 417-553-0893",
    isChain: false,
    photoKey: "cafe",
    source: "catalog",
    venueTypes: ["lounge", "bar"],
    energyLevel: 2,
  },

  // Carthage crossover nightlife
  {
    id: "nightlife-habaneros-carthage",
    name: "Habaneros Mexican Restaurant + Cantina",
    lat: 37.1799,
    lon: -94.3117,
    address: "100 Lincoln St, Carthage, MO",
    cuisines: ["mexican", "tex-mex"],
    cuisineLabel: "Cantina",
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 109,
    openingHours: "Mo-We 11:00-21:00; Th 11:00-22:00; Fr 11:00-22:30; Sa 11:00-22:00; Su 11:00-21:00",
    phone: "+1 417-237-9335",
    isChain: false,
    photoKey: "mexican",
    source: "catalog",
    venueTypes: ["bar"],
    energyLevel: 2,
  },
  {
    id: "nightlife-lucky-j-carthage",
    name: "Lucky J Steakhouse & Arena",
    lat: 37.137524,
    lon: -94.268333,
    address: "11664 E Fir Rd, Carthage, MO",
    cuisines: ["steakhouse", "american"],
    cuisineLabel: "Steakhouse / Arena Bar",
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 128,
    openingHours: "Mo-Fr 17:00-22:00; Sa 11:00-22:00; Su 11:00-15:00",
    phone: "+1 417-358-2370",
    website: "https://luckyjarena.com/steakhouse/",
    isChain: false,
    photoKey: "steak",
    source: "catalog",
    venueTypes: ["bar"],
    energyLevel: 2,
  },
  {
    id: "nightlife-woodshed-carthage",
    name: "The Woodshed Steak & Burger House",
    lat: 37.17677,
    lon: -94.31139,
    address: "311 S Main St, Carthage, MO",
    cuisines: ["american", "burgers", "steakhouse"],
    cuisineLabel: "Bar & Grill",
    priceLevel: 2,
    rating: 4.8,
    reviewCount: 37,
    openingHours: "unknown",
    phone: "+1 417-358-2707",
    isChain: false,
    photoKey: "steak",
    source: "catalog",
    venueTypes: ["bar"],
    energyLevel: 2,
  },
];
