import type { NightlifePlace } from "./types";

// County-wide nightlife safety net. Live discovery is still merged in first.
export const JASPER_COUNTY_NIGHTLIFE_CATALOG: NightlifePlace[] = [
  {
    id: "nightlife-flag-city-brewing",
    name: "Flag City Brewing",
    lat: 37.1416,
    lon: -94.4698,
    address: "618 W 4th St, Webb City, MO",
    cuisines: ["other"],
    cuisineLabel: "Brewery / Taproom",
    priceLevel: 2,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: null,
    website: null,
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["brewery", "bar"],
    energyLevel: 1,
  },
  {
    id: "nightlife-aussies-carl-junction",
    name: "Aussie's",
    lat: 37.159756,
    lon: -94.539375,
    address: "502 Briarbrook Dr, Carl Junction, MO",
    cuisines: ["american", "burgers"],
    cuisineLabel: "Sports Bar",
    priceLevel: 2,
    rating: null,
    reviewCount: null,
    openingHours: "Mo-Tu 11:00-21:00; We-Th 11:00-22:00; Fr 11:00-01:00; Sa 09:00-01:00; Su 09:00-21:00",
    phone: null,
    website: null,
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["bar", "pub"],
    energyLevel: 2,
  },
  {
    id: "nightlife-dead-cow-carterville",
    name: "Dead Cow Saloon and Grill",
    lat: 37.149215,
    lon: -94.438933,
    address: "328 E Main St, Carterville, MO",
    cuisines: ["american", "bbq", "burgers"],
    cuisineLabel: "Saloon / Bar & Grill",
    priceLevel: 2,
    rating: null,
    reviewCount: null,
    openingHours: "Mo-Th 11:00-23:00; Fr-Sa 11:00-24:00; Su 10:00-24:00",
    phone: "+1 417-673-2833",
    website: null,
    isChain: false,
    photoKey: "bbq",
    source: "catalog",
    venueTypes: ["bar", "pub"],
    energyLevel: 2,
  },
  {
    id: "nightlife-beard-engine-alba",
    name: "Beard Engine Brewing Co.",
    lat: 37.2382073,
    lon: -94.4179577,
    address: "208 Main St, Alba, MO",
    cuisines: ["other"],
    cuisineLabel: "Brewery / Taproom",
    priceLevel: 2,
    rating: null,
    reviewCount: null,
    openingHours: "Mo-Th off; Fr 14:00-22:00; Sa 12:00-20:00; Su 13:00-18:00",
    phone: "+1 417-525-4900",
    website: "https://www.beardenginebrewco.com/",
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["brewery", "pub", "bar"],
    energyLevel: 1,
  },
];
