import type { NightlifePlace } from "./types";

// County-wide nightlife safety net, re-audited September 2026.
// Live discovery is still merged in first; these records correct known stale
// local names and guarantee a few verified county anchors.
export const JASPER_COUNTY_NIGHTLIFE_CATALOG: NightlifePlace[] = [
  {
    id: "nightlife-flag-city-brewing",
    name: "Flag City Brewing",
    lat: 37.1416,
    lon: -94.4698,
    address: "618 W 4th St, Webb City, MO",
    cuisines: ["other"],
    cuisineLabel: "Brewery / Taproom",
    priceLevel: 2,
    rating: null,
    reviewCount: null,
    openingHours: "Mo-Tu off; We-Th 16:00-22:00; Fr-Sa 14:00-22:00; Su off",
    phone: "+1 417-437-0164",
    website: null,
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["brewery", "bar"],
    energyLevel: 1,
  },
  {
    id: "nightlife-aussies-carl-junction",
    name: "Joe's 19th Hole",
    lat: 37.159756,
    lon: -94.539375,
    address: "502 Briarbrook Dr, Carl Junction, MO",
    cuisines: ["american", "burgers"],
    cuisineLabel: "Bar & Grill",
    priceLevel: 1,
    rating: null,
    reviewCount: null,
    openingHours: "unknown",
    phone: "+1 417-649-6777",
    website: "https://www.briarbrookgolfcourse.com/",
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["bar", "pub"],
    energyLevel: 2,
  },
  {
    id: "nightlife-famos-on-66-carterville",
    name: "Famos on 66",
    lat: 37.149215,
    lon: -94.438933,
    address: "328 E Main St, Carterville, MO",
    cuisines: ["italian", "bbq", "burgers", "american"],
    cuisineLabel: "Restaurant / Cocktails",
    priceLevel: 2,
    rating: null,
    reviewCount: null,
    openingHours: "Mo-We off; Th-Su 11:00-21:00",
    phone: "+1 417-308-5667",
    website: "https://famos66.com/",
    isChain: false,
    photoKey: "italian",
    source: "catalog",
    venueTypes: ["bar"],
    energyLevel: 1,
  },
  {
    id: "nightlife-beard-engine-alba",
    name: "Beard Engine Brewing Co.",
    lat: 37.2382073,
    lon: -94.4179577,
    address: "208 Main St, Alba, MO",
    cuisines: ["other"],
    cuisineLabel: "Brewery / Taproom",
    priceLevel: 2,
    rating: null,
    reviewCount: null,
    openingHours: "Mo-Th off; Fr 14:00-22:00; Sa 12:00-20:00; Su 13:00-18:00",
    phone: "+1 417-525-4900",
    website: "https://www.beardenginebrewco.com/",
    isChain: false,
    photoKey: "american",
    source: "catalog",
    venueTypes: ["brewery", "pub", "bar"],
    energyLevel: 1,
  },
];
