// Assemble machine-readable reporting only; never touches implementation.
import fs from 'node:fs';
import crypto from 'node:crypto';
const stem='audit/seasonal-discovery-coverage-audit-1-2026-09-29';
const dir='audit/seasonal-discovery-coverage-audit-1-evidence';
const read=name=>JSON.parse(fs.readFileSync(dir+'/'+name,'utf8'));
const probe=read('deterministic-probes.json'),live=read('live-provider-observations.json'),render=read('react-render-evidence.json'),references=read('reference-set.json');
const findings=[
 {id:'F01',severity:'IMPORTANT',classes:['SOURCE COVERAGE GAP'],title:'Seasonal acquisition is materially incomplete',proof:'Carthage has 281 raw candidates, none seasonally classified. Aurora Maize, Pickin\' Patch and Exeter have in-radius current-season evidence but never reach ingestion. Exeter OSM node 12298081054 is tourism=theme_park, absent from the actual query; the unchanged normalizer and OFF predicate accept it if supplied.',primaryCause:true,evidence:['live-provider-observations.json','deterministic-probes.json#verifiedOsmQueryMiss','exeter-osm-node.json','reference-set.json'],recommendation:'Add bounded complementary seasonal queries and maintained activity/event sources with current-year provenance. Cover theme-park/attraction/farm/trail representations with precision controls. Benchmark multiple regional origins; do not patch only seven local venues.'},
 {id:'F02',severity:'IMPORTANT',classes:['INGESTION / CLASSIFICATION GAP'],title:'Generic mazes are incorrectly classified as corn mazes',proof:'Actual Aurora OSM node 3388827330, Turtle Moon Labyrinth, has attraction=maze and is classified corn-maze. Operator historical material describes a meditation labyrinth; no corn qualification was found. A hedge-maze fixture reproduces the same rule.',primaryCause:false,evidence:['live-provider-observations.json','deterministic-probes.json#classification','reference-set.json'],recommendation:'Require positive corn/agricultural activity evidence; distinguish generic, hedge and meditation mazes. Add actual-node and generic-maze negatives alongside valid corn-maze positives.'},
 {id:'F03',severity:'IMPORTANT',classes:['FILTERING / ELIGIBILITY GAP'],title:'Visible eligibility does not integrate strict availability and lifecycle policy',proof:'Actual UI predicate lets unknown-hours live venues pass Open Now; Aurora retains Turtle Moon ON. Werehouse is retained OFF after its confirmed window in the Nov 1 fixture although isSeasonalDateSelectable is false. Structured disused tags are not handled. Strict helper tests pass because the actual UI does not call those helpers.',primaryCause:false,evidence:['deterministic-probes.json#hours','deterministic-probes.json#seasonDates','deterministic-probes.json#liveReplay','existing-availability-tests.log'],recommendation:'Define separate open, closed, unknown-hours, upcoming, finished-season and permanent-closure states, then apply one approved policy in actual UI eligibility. Keep appropriate OFF browsing; require positive current hours/date evidence for the documented strict ON policy; refresh status as time passes.'},
 {id:'F04',severity:'IMPORTANT',classes:['INGESTION / CLASSIFICATION GAP'],title:'First uniqueness map loses multi-activity evidence',proof:'Same name and rounded coordinates in C then P records leave P-only through actual transport; reversing order leaves C-only. Direct dedupe can union types, but occurs after last-write loss. Not observed as a missing-primary-live-venue cause.',primaryCause:false,evidence:['deterministic-probes.json#duplicateMultiActivity'],recommendation:'Merge types/provenance before discarding identity duplicates. Require order-independent category preservation and unique option IDs; separately validate nearby distinct-venue merge rules.'},
 {id:'F05',severity:'NON-BLOCKING',classes:['PRESENTATION / COUNT GAP','SOURCE COVERAGE GAP'],title:'Unconfirmed status is rendered Closed and Myer schedule evidence is stale',proof:'Actual OptionsOverlay renders Closed for Myer despite Schedule unconfirmed decoration. Fresh direct operator calendar has October 2026 active dates, contradicting the frozen Sept 7 note. Numeric count remains correct.',primaryCause:false,evidence:['react-render-evidence.json','reference-event-metadata.json','reference-source-retrievals.json'],recommendation:'Display schedule uncertainty distinctly; reverify and refresh current calendar in separately authorized data work. Retain provenance, checked dates and expiry/revalidation rules.'},
 {id:'F06',severity:'NON-BLOCKING',classes:['SOURCE COVERAGE GAP','PRESENTATION / COUNT GAP'],title:'Saved-only seasonal coverage is not disclosed on successful sparse queries',proof:'Valid empty live response plus local anchors returns source=merged without warning after one request. Carthage live seasonal pool consists only of two anchors. Actual outage path correctly uses fallback and warning. Count is exact, but does not describe source completeness.',primaryCause:true,evidence:['deterministic-probes.json#scenarios','live-provider-observations.json'],recommendation:'Disclose selected-category source contribution/freshness and saved-only limitations separately from provider health. Preserve honest eligible counts and distinguish sparse success from outages.'},
];
const testGaps=[
 {risk:'Provider returns qualifying corn maze but classifier drops it',existing:'No direct seasonal transport/classifier regression identified',evidence:'Known-tag positive, Exeter query miss, duplicate metadata loss'},
 {risk:'Provider returns qualifying pumpkin patch but classifier drops it',existing:'No direct seasonal transport/classifier regression identified',evidence:'Known-tag positive, alternate tag omissions, duplicate metadata loss'},
 {risk:'Open Now OFF removes closed venue',existing:'Helpers only; no actual UI seasonal predicate coverage identified',evidence:'Actual React 2/0/2 and controlled closed fixtures'},
 {risk:'Combined filters intersect',existing:'No seven-combination seasonal UI regression identified',evidence:'Seven actual-predicate union combinations'},
 {risk:'Radius excludes valid seasonal venue',existing:'General coordinates and restaurant filtering covered, not seasonal boundary',evidence:'Actual Date Night predicate boundary and reference controls'},
 {risk:'Thin but nonempty outage fallback',existing:'General fallback nonempty/warning assertion; no selected-seasonal sufficiency',evidence:'Valid-empty versus four-mirror outage with same two eligible anchors'},
 {risk:'UI count disagrees with pool',existing:'No seasonal count/options flow assertion identified',evidence:'Captured live replay, JSON round trip and actual React SSR agree; browser RPC unverified'},
 {risk:'Duplicate venue consumes option slots',existing:'No seasonal transport-to-options regression identified',evidence:'Used-ID option uniqueness and repeated-venue dedupe pass; category overwrite fails'},
 {risk:'Unknown hours versus known-closed handling',existing:'Strict helper tested; actual predicate integration unprotected',evidence:'Live Aurora and synthetic unknown-hours pass ON despite strict helper policy'},
];
const sourceFiles=['src/lib/date-night/search.ts','src/lib/date-night/types.ts','src/lib/date-night/season.ts','src/lib/date-night/availability.ts','src/lib/date-night/seasonal-catalog.ts','src/lib/date-night/jasper-county-catalog.ts','src/lib/restaurants/decorate.ts','src/lib/restaurants/hours.ts','src/lib/restaurants/geo.ts','src/lib/store.ts','src/lib/location/model.ts','src/components/date-night-home.tsx','src/components/mode-home.tsx','src/components/location-control.tsx','src/components/options-overlay.tsx','src/components/result-overlay.tsx','src/components/date-night-plan-overlay.tsx','scripts/test-support/location-provider-fixtures.mjs','scripts/location-discovery.test.mjs','src/lib/date-night/availability.test.ts'];
const sourceHashes=Object.fromEntries(sourceFiles.map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')]));
const controls=probe.liveReplay.map((r,i)=>({...r,removedBeforeNormalization:undefined,request:live.runs[i].calls.map(c=>({url:c.url,startedAt:c.startedAt,finishedAt:c.finishedAt,status:c.status,rawCandidateCount:c.rawCandidateCount,error:c.error??null,query:c.query})),serverSource:live.runs[i].result.source,warning:live.runs[i].result.warning??null,errorFallbackActivated:live.runs[i].result.source==='fallback'}));
const record={
 schemaVersion:1,title:'Pick For Us — Seasonal Discovery Coverage Audit #1',artifactDate:'2026-09-29',generatedAt:new Date().toISOString(),executionDateUtc:'2026-09-30',timezone:'America/Chicago',
 repository:{owner:'caleb1234calvin-art',name:'dinner-roulette',branch:'audit/seasonal-discovery-coverage-1',head:'4f6bf5fde5ffb1f4e99b34584ebd4e767ba39ac3',tree:'3e288318f159873b81c31d0cc994d1ca7e6291f9',frozenBase:'0a8f30dc57fcc1156342d1bfc8a07524f3125e3b',baseTree:'5f8a4a832dc1fa06be47c9945938e2a7a379fa9f',authoritativeHandoff:'docs/handoffs/active/seasonal-discovery-coverage-audit-1.md',baseDelta:['docs/handoffs/active/seasonal-discovery-coverage-audit-1.md'],implementationDelta:[],startingCheckoutClean:true,freshRemoteRefsCheckedBeforeAudit:true,verificationArtifact:dir+'/repository-verification.json',continuityNote:'TOP continuity read; stale pre-merge main/branch statements superseded by audit handoff and fetched refs.'},
 scope:{productModified:false,catalogModified:false,productionTestsModified:false,venuesAdded:false,committed:false,pushed:false,merged:false,built:false,migrated:false,deployed:false,published:false,vercelChanged:false,signedOrUploaded:false,auditEvidenceOnly:true},
 primary:{origin:probe.origin,filters:probe.filters,spookySeasonEnabled:true,favoritesOnly:false,exclusions:[],frozenClientTime:probe.frozenClientTime,sourceTrace:controls[0],stages:[{name:'raw_provider',all:281,seasonal:0},{name:'normalized_classified',all:245,seasonal:0},{name:'first_uniqueness_map',all:245,seasonal:0},{name:'live_deduped',all:232,seasonal:0},{name:'local_anchors_input',all:17,seasonal:2},{name:'merged_deduped',all:240,seasonal:2},{name:'global_season_gate',all:240,seasonal:2},{name:'distance',all:239,seasonal:2},{name:'personal_eligibility',all:239,seasonal:2},{name:'open_state_OFF',all:239,seasonal:2},{name:'category_union_final',all:2,seasonal:2},{name:'rendered_match_count',all:2,seasonal:2},{name:'options',all:2,seasonal:2}],preNormalizationRemovals:{count:36,reason:'All unnamed; none seasonally classified'},render:render,rootCause:'Source/query coverage plus sparse anchors, not a demonstrated Carthage union/radius/mood/open-OFF/count/serialization error'},
 sourceAnalysis:{productionInputs:['OSM Overpass','Jasper County ordinary catalog','Jasper County seasonal catalog'],geocodingOnly:'Nominatim',seasonalQueryTags:['leisure=maze','attraction=maze','attraction=haunted_house','attraction=pumpkin_patch'],providerRadiusMeters:80467,mirrorOrder:['https://overpass.openstreetmap.fr/api/interpreter','https://overpass.private.coffee/api/interpreter','https://maps.mail.ru/osm/tools/overpass/api/interpreter','https://overpass-api.de/api/interpreter'],serverQueryTimeoutSeconds:20,fetchAbortSeconds:22,mirrorsAreIndependentInventories:false,liveObservationsAreCompleteInventory:false,extraDiagnosticFailures:read('diagnostic-provider-query.json')},
 anchors:{totalOrdinary:15,totalSeasonal:2,bySeasonalCategory:{'haunted-house':2,'corn-maze':0,'pumpkin-patch':0},geography:'Carthage/Joplin, Jasper County; sparse coordinate-verified fallback, not comprehensive',mergedOnSuccessfulRequests:true},
 controls,referenceMethodology:references.method,referenceCandidates:references.candidates,
 category:{semantics:'union / any selected category',combinations:probe.combinations,duplicateMultiActivity:probe.duplicateMultiActivity,fixtureOptions:probe.fixtureOptions},
 radius:{semantics:'Haversine straight-line miles',earthRadiusMiles:3958.8,uiToleranceMiles:0.05,localFetchCushionMiles:1,syntheticBoundaries:probe.radius,referenceBoundaries:probe.referenceBoundary,originalProductionGpsKnown:false},
 availability:{toggles:probe.hours,seasonDates:probe.seasonDates,strictHelpersUsedByUi:false,decoratedHoursRefresh:'memoized by venues/location, no clock dependency',distinguishStates:['closed now','unknown hours','unconfirmed seasonal calendar','upcoming season','finished/not operating season','permanent closure']},
 regression:{existingTests:[{path:'src/lib/date-night/availability.test.ts',pass:6,fail:0,log:dir+'/existing-availability-tests.log'},{path:'scripts/location-discovery.test.mjs',pass:10,fail:0,log:dir+'/existing-location-tests.log'}],testGaps,productionSuiteChanged:false,fullSuiteRun:false,browserAcceptance:false,reactSourceRenderExecuted:true,frameworkRpcVerified:false},
 findings,severityCounts:{BLOCKER:0,IMPORTANT:4,'NON-BLOCKING':2},severityRationale:'No demonstrated blocker in current primary reproduction: known-closed filtering, union, radius, count, pick/options and incomplete-plan guard function for captured data. Unknown/lifecycle and metadata defects merit remediation; no actual currently known-closed venue shown passing ON, real permanently closed venue asserted shown, or material radius/count corruption established. Not release approval.',
 nonRecommendations:['Hard-code only seven Carthage leads','Import the audit reference set as catalog edits','Inflate counts with weak/nonqualifying/duplicate/stale venues','Weaken distance, Open Now or category rules','Claim provider completeness','Treat permanent closure, ended season, closed tonight and unknown hours interchangeably','Substitute pure-helper passes or SSR for complete UI/browser/RPC acceptance'],
 limitations:['Original production GPS/time/network trace unavailable; declared city-center origin and frozen Chicago time used','Public results are time-sensitive and not a complete inventory','Operator, municipal, tourism, directory, historic, conflicting and unavailable sources explicitly distinguished','Cadaver reliable coordinate and 2026 operation not verified; Forest operating/closure conflict unresolved despite fresh published 2026 calendar','Chromium absent; installation failed invalid/truncated ZIP; no full browser/RPC/CSS/hydration/device test','React source SSR uses stubbed hooks/state/effects/subcomponents/portal; exact action/predicate/labels executed','Dependency tree reused locally on Node 24.19.0; no fresh install, build, full suite or CI claim','Random choice order varies; membership/count/category behavior is the evidence','Source and final implementation hashes do not imply production redeployment verification'],
 sourceHashes,report:stem+'.md',evidenceDirectory:dir,evidenceManifest:dir+'/evidence-manifest.json',finalState:'SEASONAL DISCOVERY AUDIT — REMEDIATION RECOMMENDED',stop:true,
};
fs.writeFileSync(stem+'.json',JSON.stringify(record,null,2)+'\n');
console.log(JSON.stringify({report:stem+'.json',findings:findings.length,references:references.candidates.length,controls:controls.length,testsPassed:16,finalState:record.finalState}));
